[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npx prisma db push && npx tsx src/scripts/seedAdmin.ts && node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
PORT = "5000"
